name: Chairs
version: 1.5
description: Let players sit on stairs and slabs.
author: spoothie
main: io.github.arownic.chairs.Chairs
commands:
    chairs:
        description: Reloads the Chairs configuration file.
        usage: /chairs reload